version: '3.9'

services:

  mongo:
    container_name: mongo-db
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
    volumes:
      - my-db:/var/lib/mongodb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpassword
      ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbpassword@mongo:27017/
volumes:
  my-db:
