# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresql:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080