
# Use root/example as user/password credentials
version: '3.1'

services:

  mysqldb:
    image: mysql:8.0.31
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword

  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1